### ISSUE TITLE
Got "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by Frozzy6** [Ant1mas/number-to-words-ru#1]
Got this https://guides.github.com/features/mastering-markdown/error while importing to node application.

I checked your code and found you don't using a global window object.
Can you change webpack config suggested to [global: 'this'](https://webpack.js.org/configuration/output/#outputglobalobject) and update new version to npm please. (I think it could be helpful)

**Comment by Ant1mas** [comment]
I added `globalObject: 'this'` in webpack config.
