### ISSUE TITLE
Compilation error in TypeScript project

### ISSUE THREAD

**Issue by Mishelles** [Ant1mas/number-to-words-ru#12]
Hello! I have an error in my TypeScript project. I use version 2.2.3 of **number-to-words** package.

My import statement is:
```
import numberToWordsRu from 'number-to-words-ru';
```

The error is:
```
node_modules/number-to-words-ru/index.d.ts:90:18 - error TS2304: Cannot find name 'numberToWordsRu'.

90   export default numberToWordsRu;

```

**Comment by Ant1mas** [comment]
@Mishelles, у меня не появляется такая ошибка на тестовом проекте через Webpack. Я внес исправления в файл index.d.ts и думаю, что эта ошибка теперь исправлена. Пожалуйста проверьте решена ли эта проблема у вас с версией number-to-words-ru **2.2.4**.
