### ISSUE TITLE
проблема с использованием в TS (NestJS) проекте

### ISSUE THREAD

**Issue by gftx** [Ant1mas/number-to-words-ru#23]
вызывается такая ошибка при добавлении в  проект: 
 
 error TS2307: Cannot find module 'number-to-words-ru' or its corresponding type declarations
<img width="1033" alt="Screenshot 2022-05-24 at 12 35 40" src="https://user-images.githubusercontent.com/56353429/170000838-234bb0d9-8e29-43b8-9ee7-756bb81dee0b.png">
.

**Comment by Ant1mas** [comment]
@gftx Проверил на чистом [шаблоне стартера NestJS](https://github.com/nestjs/typescript-starter), у меня такой ошибки не проявляется. 
![nest](https://user-images.githubusercontent.com/7397158/170055385-030ddfc3-8792-4d4f-80e0-25d85ff4cefb.png)
Такая ошибка (TS2307) была только ДО установки `number-to-words-ru` в проект. После установки (`npm install number-to-words-ru`) ошибка сразу пропадает.
Проверьте добавлен ли модуль `number-to-words-ru` в файле `package.json` и есть ли в проекте папка с файлами от модуля (`/node_modules/number-to-words-ru`)

**Comment by gftx** [comment]
все да, разобрался
спасибо
у меня докер контейнер просто не заново собрался а собрался со старыми (без number-to-words) 
пересобрал и все ок
