### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by alexandropavlov** [Ant1mas/number-to-words-ru#27]
Проблема возникает на старых браузерах.
`structuredClone` добавлена в новые версии браузеров не так давно - с марта 2022
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
Соответственно проблема возникает у пользователей, кто давно не обновлял браузер.

Предлагаю использовать вызовы через polyfill для лучшей поддержки в браузерах, например:
https://www.npmjs.com/package/@ungap/structured-clone

**Comment by Ant1mas** [comment]
@alexandropavlov, спасибо за полезную информацию. В версии `2.4.1` добавлен polyfill, решающий эту проблему.
