### ISSUE TITLE
при вводе 20000 пишет 20 тысячи, а правильно 20 тысяч

### ISSUE THREAD

**Issue by Sergey-Ubogov** [Ant1mas/number-to-words-ru#5]
при вводе 20000 пишет 20 тысячи, а правильно 20 тысяч

**Comment by Ant1mas** [comment]
Эта проблема была исправлена в версии 2.0.0.
@Sergey-Ubogov, возможно у вас установлена версия ниже 2.0.0
На [демо странице](https://ant1mas.github.io/number-to-words-ru/) значение "20000" корректно переводится.
